=== SharexNju/application-integration/smallspider/src/main/resources/stockcomments.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://118.89.171.93/"
           xmlns="http://118.89.171.93/"
           elementFormDefault="qualified">

    <xs:element name="stockComments">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="stockCode" type="xs:string"/>
                <xs:element name="comments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="comment" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="url" type="xs:string"/>
                                        <xs:element name="source" type="xs:string"/>
                                        <xs:element name="date" type="xs:string"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== SharexNju/application-integration/smallspider/src/main/resources/standard_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<stockComments xmlns="http://118.89.171.93/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://118.89.171.93/ stockcomments.xsd">
    <stockCode>600000</stockCode>
    <comments>
        <comment>
            <title>dwa</title>
            <url>dwa</url>
            <source>dwa</source>
            <date>dwadwa</date>
        </comment>
        <comment>
            <title>dd</title>
            <url>aw</url>
            <source>sdws</source>
            <date>dwas</date>
        </comment>
    </comments>
</stockComments>
